apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - apk add --no-cache curl && sleep 3600 # install curl
    tty: true  # Enables pseudo-terminal for interactive use